########################################################
# Créer un site statique Hugo/Ananke/Disqus/Formspree  #
# et automatiser le déploiement avec Netlify et GitHub #
########################################################


########################################################
# jeu de données
########################################################

# global

installation_path=~/
site_name=ananke_blog
theme_name=gohugo-theme-ananke
site_title="Titre du site"
site_url=https://urldusite.com
site_language=en-us

# config.toml

themes_directory=themes
meta_data_format=yaml
default_content_language=en
section_pages_menu=main
paginate=3
google_analytics=
enable_robots_txt=true
# disqus
disqus_shortname=
# sitemap
change_freq=monthly
priority=0.5
filename=sitemap.xml
# params
favicon=
description="The last theme you'll ever need. Maybe."
facebook=
twitter=https://twitter.com/GoHugoIO
instagram=
youtube=
github=
gitlab=
linkedin=
mastodon=
slack=
stackoverflow=
background_color_class=bg-black
body_classes="avenir bg-near-white"
post_content_classes=
show_reading_time=false
featured_image=/images/gohugo-default-sample-hero-image.jpg
recent_posts_number=2
custom_css=


########################################################
# initialiser un site hugo
########################################################

# installer snapd

sudo apt-get install snapd
sudo snap set system refresh.retain=2

# installer hugo

snap install hugo

# initialiser hugo

cd $installation_path
hugo new site $site_name


########################################################
# ajouter le thème ananke
########################################################

# installer git

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git

# installer le thème ananke

cd $site_name
git init
git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/$theme_name


########################################################
# créer le fichier config.toml
########################################################

echo -e "title = \""$site_title"\"" > config.toml
echo -e "baseURL = \""$site_url"\"" >> config.toml
echo -e "languageCode = \""$site_language"\"" >> config.toml
echo -e "theme = \""$theme_name"\"" >> config.toml
echo -e "themesDir = \""$themes_directory"\"" >> config.toml
echo -e "\nMetaDataFormat = \""$meta_data_format"\"" >> config.toml
echo -e "DefaultContentLanguage = \""$default_content_language"\"" >> config.toml
echo -e "SectionPagesMenu = \""$section_pages_menu"\"" >> config.toml
echo -e "Paginate = "$paginate" # this is set low for demonstrating with dummy content. Set to a higher number" >> config.toml
echo -e "googleAnalytics = \""$google_analytics"\"" >> config.toml
echo -e "enableRobotsTXT = "$enable_robots_txt"" >> config.toml
echo -e "disqusShortname = \""$disqus_shortname"\"" >> config.toml
echo -e "\n[sitemap]" >> config.toml
echo -e "\tchangefreq = \""$change_freq"\"" >> config.toml
echo -e "\tpriority = "$priority"" >> config.toml
echo -e "\tfilename = \""$filename"\"" >> config.toml
echo -e "\n[params]" >> config.toml
echo -e "\tfavicon = \""$favicon"\"" >> config.toml
echo -e "\tdescription = \""$description"\"" >> config.toml
echo -e "\tfacebook = \""$facebook"\"" >> config.toml
echo -e "\ttwitter = \""$twitter"\"" >> config.toml
echo -e "\tinstagram = \""$instagram"\"" >> config.toml
echo -e "\tyoutube = \""$youtube"\"" >> config.toml
echo -e "\tgithub = \""$github"\"" >> config.toml
echo -e "\tgitlab = \""$gitlab"\"" >> config.toml
echo -e "\tlinkedin = \""$linkedin"\"" >> config.toml
echo -e "\tmastodon = \""$mastodon"\"" >> config.toml
echo -e "\tslack = \""$slack"\"" >> config.toml
echo -e "\tstackoverflow = \""$stackoverflow"\"" >> config.toml
echo -e "\t# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with \"bg-\"" >> config.toml
echo -e "\tbackground_color_class = \""$background_color_class"\"" >> config.toml
echo -e "\tbody_classes = \""$body_classes"\"" >> config.toml
echo -e "\tpost_content_classes = \""$post_content_classes"\"" >> config.toml
echo -e "\tshow_reading_time = "$show_reading_time"" >> config.toml
echo -e "\tfeatured_image = \""$featured_image"\"" >> config.toml
echo -e "\trecent_posts_number = "$recent_posts_number"" >> config.toml
echo -e "\tcustom_css = [\""$custom_css"\"]" >> config.toml


########################################################
# ajouter des articles de blog
########################################################

# générer un article par défaut dans la section posts ( suivant le modèle /archetypes/default.md)

hugo new posts/new_draft_post.md
echo "This is a post generated by Hugo, using the default.md archetype. The *posts* section is automatically added to the main menu" >> content/posts/new_draft_post.md


########################################################
# créer une page statique et l'ajouter au menu principal
########################################################

echo "---" > content/about.md
echo "title: \"About\"" >> content/about.md
echo "date: `date -Iseconds`" >> content/about.md
echo "draft: true" >> content/about.md
echo "menu: main" >> content/about.md
echo "---" >> content/about.md
echo -e "\nThis is a static page named *About*. This page is accessible from the main menu." >> content/about.md


########################################################
## tests
########################################################

hugo
hugo server -D
